# Generated by Django 4.2.2 on 2024-06-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "purchase_price"],
                "permissions": [
                    (
                        "may_cancel_the_publication_product",
                        "may cancel the publication product",
                    ),
                    ("can_edit_description_product", "Can edit description product"),
                    ("can_change_category_product", "Can change category product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
